services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./assets:/usr/share/nginx/html
    ports:
      - "8082:80"
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - ./assets:/usr/src/app/assets
  workers:
    build: ./workers
    volumes:
      - ./workers:/usr/src/app
  redis:
    image: redis
    volumes:
      - ./redis:/data
  postgres:
    image: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
